"""Add authoring session and draft models

Revision ID: c6e2c87f35cd
Revises: 0001_initial_mvp
Create Date: 2026-03-09 23:54:24.204125
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'c6e2c87f35cd'
down_revision = '0001_initial_mvp'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authoring_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('intent_brief', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authoring_sessions_status'), 'authoring_sessions', ['status'], unique=False)
    op.create_table('authoring_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('spec_json', sa.JSON(), nullable=False),
    sa.Column('lint_warnings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['authoring_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'revision', name='uq_session_revision')
    )
    op.create_index(op.f('ix_authoring_drafts_session_id'), 'authoring_drafts', ['session_id'], unique=False)
    op.drop_index(op.f('ix_workflow_definitions_workflow_id'), table_name='workflow_definitions')
    op.create_index(op.f('ix_workflow_definitions_workflow_id'), 'workflow_definitions', ['workflow_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_definitions_workflow_id'), table_name='workflow_definitions')
    op.create_index(op.f('ix_workflow_definitions_workflow_id'), 'workflow_definitions', ['workflow_id'], unique=False)
    op.drop_index(op.f('ix_authoring_drafts_session_id'), table_name='authoring_drafts')
    op.drop_table('authoring_drafts')
    op.drop_index(op.f('ix_authoring_sessions_status'), table_name='authoring_sessions')
    op.drop_table('authoring_sessions')
    # ### end Alembic commands ###
