from __future__ import annotations

import json
import os
import sys
from pathlib import Path


def main() -> int:
    prompt = sys.stdin.read()
    if "Pipeliner Claude Executor Task" not in prompt:
        print("missing expected prompt", file=sys.stderr)
        return 2

    task_file = os.getenv("PIPELINER_EXECUTOR_TASK_FILE")
    if not task_file:
        print("missing PIPELINER_EXECUTOR_TASK_FILE", file=sys.stderr)
        return 2

    payload = json.loads(Path(task_file).read_text(encoding="utf-8"))
    for target in payload["targets"]:
        path = Path(target["absolute_path"])
        kind = target["kind"]
        if kind == "file":
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text("# generated by stdin executor\n", encoding="utf-8")
        else:
            path.mkdir(parents=True, exist_ok=True)
            (path / "index.txt").write_text("generated by stdin executor\n", encoding="utf-8")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
